try {
    hello ();
} catch (error) {
    console.log(error);
}
//tambien
try {
    onotherFn();
} catch {
    console.log("esto es un error")
}